### ISSUE TITLE
Seems the official bot is running an older version?

### ISSUE THREAD

**Issue by ktsuttlemyre** [silvenlily/spindle#1]
The |unlink command isn't working for me. Does the bot need to be updated to the latest code?

**Comment by silvenlily** [comment]
huh,
sorry I didn't see this till now, tbh haven't worked on spindle in a few months
I'll take a look at this in a few days. The official bot is deffo running the latest version though so prbly a bug.

**Comment by silvenlily** [comment]
fixed
https://github.com/silvenlily/spindle/commit/c86e225ca063589421c15812638f81c39b293337
